name = "GraphicalLassoQUIC"
uuid = "db53d3f2-1e72-4de5-901c-ab93047c33dc"
authors = ["mlkrock <mitchell.krock@colorado.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
Random = "1.11.0"
julia = "1"
